### ISSUE TITLE
Request: Ability to easily switch to beta branch via configuration

### ISSUE THREAD

**Issue by pksm-resdev** [luxusburg/docker-foundry#14]
Thank you for open sourcing the repository from the beginning.

I have a request - would it be possible to easily use the beta branch by setting environment variables in docker-compose or similar?

While forking the repo and editing start.sh would achieve this, it would be great if there was an easier way to do it.

I'd like to be able to select the beta branch seamlessly through configuration.

Thank you for considering this request.

**Comment by luxusburg** [comment]
Hi, sounds lile a good Idea will impliment it tomorrow and push it to the main branch

**Comment by luxusburg** [comment]
Has been added in the merge:
- #19
