### ISSUE TITLE
steam_appid.txt not found

### ISSUE THREAD

**Issue by kimish1ma** [luxusburg/docker-foundry#22]
When enabling the beta branch with environment variables and running the `docker compose up -d` command to start the container, the `steam_appid.txt` file is not being created in the `./server` directory in the same directory.
This causes the value of steam_appid to be blank, and the server cannot start up properly.

```
foundry | cat: can't open '/home/foundry/server_files/steam_appid.txt': No such file or directory
foundry | steam_appid:
```

As a solution, after running `docker compose up -d` and the container failed to start, I manually created the `steam_appid.txt` file in the `./server` directory, wrote in the AppID, and ran `docker compose restart`. 
This allowed the AppID to be read, and the server started up normally.

Is this an issue with my environment or an issue with SteamCMD?
Any help would be appreciated.

**Comment by luxusburg** [comment]
Hello, 

The first time I heard about such a problem, I tried a few times with the env set for the beta branch, and it worked.

So the program stopped at that error?
