### ISSUE TITLE
Add instructions to persist serverfiles

### ISSUE THREAD

**Issue by Requion** [luxusburg/docker-foundry#5]
As an administrator i would like to be able to persist the files downloaded through steamcmd.

This way i don't have to re-download them each time the container is removed but the files will still be updated by steamcmd.

**Comment by Requion** [comment]
I just saw that this is already addressed here: https://github.com/luxusburg/docker-foundry/blob/main/files%2Fstart.sh#L4

I will have to test something. Maybe this can be closed.

**Comment by luxusburg** [comment]
I thought I made them persistent in the server folder?

**Comment by Requion** [comment]
Yes you made them persistent already. I was just confused while testing the X11 bug because the serverfiles got downloaded repeatedly. But this was probably usererror on my side.

We can close this issue. If i should observe this behaviour i can reopen.
