### ISSUE TITLE
add more env options

### ISSUE THREAD

**Issue by ripsnortntear** [luxusburg/docker-foundry#9]
Please add some more options. the full list is

  - SERVER_WORLD_NAME=examplename
  - SERVER_PASSWORD=StrongPassword
  - PAUSE_SERVER_WHEN_EMPTY=false
  - AUTOSAVE_INTERVAL=300
  - SERVER_IS_PUBLIC=false
  - SERVER_PORT=3724
  - SERVER_QUERY_PORT=27015
  - SERVER_NAME='github/luxusburg'
  - SERVER_MAX_PLAYERS=32

also adding ```restart: unless-stopped``` to the docker compose will help it from crashing

is it possible to run this with `PUID` 'GUID' environment variables as well so that it creates files within the users group?

**Comment by Requion** [comment]
Hi, the available env vars are listed in the [Readme](https://github.com/luxusburg/docker-foundry?tab=readme-ov-file#environment-variables-game-settings). Those are the options for Docker (Compose) and is translated to the app.cfg.

If these env vars aren't recognized then it probably is a bug.

And the User/Group topic is currently being worked on for version 1.3 of this image.
